Livis.Market/Livis.Market/Models/ViewModel/LayoutViewModel.cs
using Livis.Market.Models.ViewModel.ComponentViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Livis.Market.Models.ViewModel
{
    public class LayoutViewModel
    {
        public FooterViewModel Footer { get; set; }

        public HeaderViewModel Header { get; set; }

        public string Title { get; set; }
    }
}

Livis.Market/Livis.Market/Controllers/FindUserController.cs
using System;
using System.Threading.Tasks;
using Livis.Market.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace Livis.Market.Controllers
{
    public class FindUserController : BaseLivisServerController
    {
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> UpdateInfo(FindUsernameView model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByNameAsync(model.Username);
                if (user == null)
                {
                    model = null;
                    PopulateErrorMessage("Unable found user match your condition.");
                }
                else
                {
                    if(!string.IsNullOrEmpty(model.Password?.Trim()))
                    {
                        await ChangePassword(model.Password?.Trim(), user);
                    }
                    if(model.IsLock)
                    {
                        var result = await _userManager.SetLockoutEnabledAsync(user, true);
                        if (result.Succeeded)
                        {
                            result = await _userManager.SetLockoutEndDateAsync(user, DateTimeOffset.MaxValue);
                        }
                    }
                    else
                    {
                        var result = await _userManager.SetLockoutEnabledAsync(user, true);
                        if (result.Succeeded)
                        {
                            await _userManager.SetLockoutEndDateAsync(user, null);
                            result = await _userManager.ResetAccessFailedCountAsync(user);
                        }
                    }
                    PopulateErrorMessage("Update Successfully");
                }
            }

            return View("Index", model);
        }

        [HttpPost]
        public async Task<IActionResult> Index(FindUsernameView model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByNameAsync(model.Username);
                if(user ==  null)
                {
                    model = null;
                    PopulateErrorMessage("Unable found user match your condition.");
                }
                else
                {
                    model.Username = user.UserName;
                    model.IsLock = await _userManager.IsLockedOutAsync(user);
                    PopulateErrorMessage(string.Empty);
                }
            }
           
            return View(model);
        }
    }
}

Livis.Market/Livis.Market/Controllers/LivisServerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Livis.Market.Controllers
{
    [Authorize(Roles = "Admin")]
    public class LivisServerController : BaseLivisServerController
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Livis.Market/Livis.Market/Controllers/OrganisationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using LivinMarket.Organisation.Exceptions.Business;
using LivinMarket.Organisation.Model.Commands.Business;
using LivinMarket.Organisation.Model.Queries.Business;
using Livis.Market.Data;
using Livis.Market.Models.ViewModel;
using Livis.Market.Utilities.Helper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Livis.Market.Controllers
{
    [Authorize(Roles = "Admin")]
    public class OrganisationController : BaseLivisServerController
    { 
        public async Task<IActionResult> Index()
        {
            var response = await _processor.ProcessQueryAsync<OrganisationQuery, OrganisationResponse>(new OrganisationQuery()
            {
                NameOrId = string.Empty
            });
            var organisations = response.Organisations;
            var models = Mapper.Map<List<Organisation>, List<OrganisationView>>(organisations.ToList());
            var listModel = models.ToList();
            listModel.ForEach(x => 
                x.ViewUrl = $"/Organisation/Update?orgId={x.OrganisationId}"
            );
            listModel.ForEach(x =>
                x.EditUrl = $"/Organisation/Update?orgId={x.OrganisationId}"
            );
            return View(listModel);
        }

        public async Task<IActionResult> Create()
        {
            await PopulateRegistrationStatus(string.Empty);
            return View();
        }

        public async Task<IActionResult> Update(Guid orgId)
        {
            var response = await _processor.ProcessQueryAsync<OrganisationQuery, OrganisationResponse>(new OrganisationQuery() {
                NameOrId = orgId.ToString()
            });
            var organisation = response.Organisations.FirstOrDefault();
            if(organisation == null)
            {
               await PopulateRegistrationStatus("Not found any organsaition match your condition.");
            }
            else
            {
               await PopulateRegistrationStatus(string.Empty);
            }
            var model = _mapper.Map<Livis.Market.Data.Organisation, OrganisationViewModel>(organisation);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Update(OrganisationViewModel model)
        {
            if (ModelState.IsValid)
            {
                var command = _mapper.Map<OrganisationViewModel, UpdateOrganisationCommand>(model);
                try
                {
                    await _processor.ProcessCommandAsync<UpdateOrganisationCommand>(command);
                }
                catch (OrgNotFoundException ex)
                {
                    await PopulateRegistrationStatus(ex.Message);
                    return View();
                }
            }
            await PopulateRegistrationStatus(string.Empty);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(OrganisationViewModel model)
        {
            if (ModelState.IsValid)
            {
                var command = _mapper.Map<OrganisationViewModel, AddOrganisationCommand>(model);
                try
                {
                    string scheme = Url.ActionContext.HttpContext.Request.Scheme;
                    command.ConfirmationLink = Url.Action("VerifyAgency", "Confiramtion", null, scheme);
                    await _processor.ProcessCommandAsync<AddOrganisationCommand>(command);
                    return RedirectToAction(nameof(Update), new { orgId = command.OrganisationId });
                }
                catch(UserExistedException ex)
                {
                    await PopulateRegistrationStatus(ex.Message);
                    return View();
                }
            }
            await PopulateRegistrationStatus(string.Empty);
            return View(model);
        }

        private async Task PopulateRegistrationStatus(string errorMessage)
        {
            ViewBag.RegistrationStatus = new SelectList(ComponentsHelper.GetRegistrationStatusList(), "Key", "Value");
            ViewBag.ErrorMessage = errorMessage;
        }
    }
}

Livis.Market/Livis.Market/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Livis.Market.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using LivinMarket.Product.Model.Queries.Business;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Livis.Market.Data;
using LivinMarket.Product.Model.Commands.Business;
using Livis.Common.Tools;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Authorization;
using Livis.Market.Utilities.Helper;

namespace Livis.Market.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProductController : BaseController
    {
        private readonly IHostingEnvironment _appEnvironment;

        public ProductController(IHostingEnvironment appEnvironment)
        {
            _appEnvironment = appEnvironment;
        }

        public async Task<ActionResult> View(string sku)
        {
            await PopulateCategories();
            var responseQuery = await _processor.ProcessQueryAsync<ProductQuery, ProductResponse>(new ProductQuery()
            {
                NameOrId = sku
            });
            var model = new ProductViewModel();
            if (responseQuery != null)
            {
                var updatedProduct = responseQuery.Products.First();
                model = new ProductViewModel()
                {
                    Sku = updatedProduct.Sku,
                    Name = updatedProduct.Name,
                    CategoryId = updatedProduct.CategoryId.Value,
                    Cost = updatedProduct.Cost.ToString("G29"),
                    Description = updatedProduct.Description,
                    Height = updatedProduct.Height.Value.ToString("G29"),
                    Length = updatedProduct.Length.Value.ToString("G29"),
                    OriginalLinks = updatedProduct.OriginalLinks,
                    ProductId = updatedProduct.ProductId,
                    Resources = updatedProduct.Resources,
                    Videos = updatedProduct.Videos,
                    Weight = updatedProduct.Weight.Value.ToString("G29"),
                    Width = updatedProduct.Width.Value.ToString("G29"),
                    SuggestedPrice = updatedProduct.SuggestedPrice.ToString("G29"),
                    Photos = updatedProduct.Photos?.Select(x => new ProductPhotoModel()
                    {
                        BlobUrl = x.BlobUrl,
                        PhotoId = x.PhotoId
                    }).ToArray(),
                    PartnerPhotos = updatedProduct.PartnerPhotos?.Select(x => new ProductPhotoForPartnerModel()
                    {
                        BlobUrl = x.BlobUrl,
                        PhotoId = x.PhotoId
                    }).ToArray(),
                    Options = !string.IsNullOrEmpty(updatedProduct.VariantOptions) ? JsonConvert.DeserializeObject<List<OptionViewModel>>(updatedProduct.VariantOptions) :
                        new List<OptionViewModel>(),
                    Variants = !string.IsNullOrEmpty(updatedProduct.VariantKeys) ? JsonConvert.DeserializeObject<List<Variant>>(updatedProduct.VariantKeys) : new List<Variant>()
                };
            }
            return View(model);
        }

        public async Task<ActionResult> Index()
        {
            var responseQuery = await _processor.ProcessQueryAsync<ProductQuery, ProductResponse>(new ProductQuery()
            {
                NameOrId = string.Empty
            });
            var model = new ProductView[] { };
            if (responseQuery.Products.Any())
            {
                model = responseQuery.Products.Select(p => new ProductView()
                {
                    Cost = p.Cost.ToString("G29"),
                    SuggestedPrice = p.SuggestedPrice.ToString("G29"),
                    Height = p.Height?.ToString("G29"),
                    Length = p.Length?.ToString("G29"),
                    Name = p.Name,
                    Sku = p.Sku,
                    Weight = p.Weight?.ToString("G29"),
                    Width = p.Width?.ToString("G29"),
                    ProductId = p.ProductId,
                    ImageUrl = p.Photos?.Count > 0 ? p.Photos.First().BlobUrl : "/images/upload.png",
                    EditUrl = "/Product/Update?sku=" + p.Sku,
                    ViewUrl = "/Product/View?sku=" + p.Sku,
                    DeleteUrl = "/Product/Delete?sku=" + p.Sku
                }).ToArray();
            }
            return View(model);
        }

        public async Task<IActionResult> Create()
        {
            await PopulateCategories();
            return View();
        }

        public async Task<IActionResult> Update(string sku)
        {
            await PopulateCategories();
            var responseQuery = await _processor.ProcessQueryAsync<ProductQuery, ProductResponse>(new ProductQuery()
            {
                NameOrId = sku
            });
            var model = new ProductViewModel();
            if (responseQuery != null)
            {
                var updatedProduct = responseQuery.Products.First();
                model = new ProductViewModel()
                {
                    Sku = updatedProduct.Sku,
                    Name = updatedProduct.Name,
                    CategoryId = updatedProduct.CategoryId.Value,
                    Cost = updatedProduct.Cost.ToString("G29"),
                    Description = updatedProduct.Description,
                    Height = updatedProduct.Height.Value.ToString("G29"),
                    Length = updatedProduct.Length.Value.ToString("G29"),
                    OriginalLinks = updatedProduct.OriginalLinks,
                    ProductId = updatedProduct.ProductId,
                    Resources = updatedProduct.Resources,
                    Videos = updatedProduct.Videos,
                    Weight = updatedProduct.Weight.Value.ToString("G29"),
                    Width = updatedProduct.Width.Value.ToString("G29"),
                    SuggestedPrice = updatedProduct.SuggestedPrice.ToString("G29"),
                    Photos = updatedProduct.Photos?.Select(x => new ProductPhotoModel() {
                        BlobUrl = x.BlobUrl,
                        PhotoId = x.PhotoId
                    }).ToArray(),
                    PartnerPhotos = updatedProduct.PartnerPhotos?.Select(x => new ProductPhotoForPartnerModel() {
                        BlobUrl = x.BlobUrl,
                        PhotoId = x.PhotoId
                    }).ToArray(),
                    Options = !string.IsNullOrEmpty(updatedProduct.VariantOptions) ? JsonConvert.DeserializeObject<List<OptionViewModel>>(updatedProduct.VariantOptions) :
                        new List<OptionViewModel>(),
                    Variants = !string.IsNullOrEmpty(updatedProduct.VariantKeys) ? JsonConvert.DeserializeObject<List<Variant>>(updatedProduct.VariantKeys) : new List<Variant>(),
                    Prices = !string.IsNullOrEmpty(updatedProduct.Prices) ? JsonConvert.DeserializeObject<List<ProductPrice>>(updatedProduct.Prices).Select(x => new ProductPriceView() {
                        CustomerGroup = x.CustomerGroup,
                        Price = x.Price.ToString("G29"),
                        CustomerGroupName = x.CustomerGroup.GetDisplayName()
                    }).ToList() : new List<ProductPriceView>()
                };
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string sku)
        {
            try
            {
                await _processor.ProcessCommandAsync<DeleteProductCommand>(new DeleteProductCommand()
                {
                    Sku = sku
                });
                return Json(new { @success = true, @message = string.Empty });
            }
            catch (Exception ex)
            {
                return Json(new { @success = false, @message = ex.Message });
            }
        }

        [HttpPost]
        public async Task<IActionResult> Update(ProductViewModel model)
        {
            if (ModelState.IsValid)
            {
                var currentUser = await _userContext.GetCurrentUser();
                var updateProductCommand = new UpdateProductCommand()
                {
                    Name = model.Name,
                    CategoryId = model.CategoryId,
                    Cost = string.IsNullOrEmpty(model.Cost) ? 0 : Decimal.Parse(model.Cost),
                    Description = model.Description,
                    Height = string.IsNullOrEmpty(model.Height) ? 0 : Decimal.Parse(model.Height),
                    Length = string.IsNullOrEmpty(model.Length) ? 0 : Decimal.Parse(model.Length),
                    OriginalLinks = model.OriginalLinks,
                    Width = string.IsNullOrEmpty(model.Width) ? 0 : Decimal.Parse(model.Width),
                    Weight = string.IsNullOrEmpty(model.Weight) ? 0 : Decimal.Parse(model.Weight),
                    Videos = model.Videos,
                    SuggestedPrice = string.IsNullOrEmpty(model.SuggestedPrice) ? 0 : Decimal.Parse(model.SuggestedPrice),
                    Resources = model.Resources,
                    Photos = model.Photos?.Select(x => new ProductPhoto()
                    {
                        BlobUrl = x.BlobUrl
                    }).ToArray(),
                    PartnerPhotos = model.PartnerPhotos?.Select(x => new ProductPhotoForPartner()
                    {
                        BlobUrl = x.BlobUrl
                    }).ToArray(),
                    ProductId = model.ProductId,
                    Sku = model.Sku,
                    VariantOptions = (model.Options != null && model.Options.Count > 0) ?
                        JsonConvert.SerializeObject(model.Options) : string.Empty,
                    VariantKeys = (model.Variants != null && model.Variants.Count > 0) ?
                        JsonConvert.SerializeObject(model.Variants) : string.Empty,

Livis.Market/Livis.Market/Views/Shared/_Layout.cshtml
@using Livis.Market.Infrastructure.Constants;
@model Livis.Market.Models.ViewModel.LayoutViewModel
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@Model.Title</title>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="generator" content="Livis" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <title>@Model.Title</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/css/Editor.css" />
        <link rel="stylesheet" href="~/css/main.css" />
        <link rel="stylesheet" href="~/css/livis.css" />
        <link rel="stylesheet" href="~/lib/nicelabel/css/jquery-nicelabel.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/css/Editor.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/main.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/livis.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/lib/nicelabel/css/jquery-nicelabel.css" asp-append-version="true" />
    </environment>
</head>
<body>
    @{ Html.RenderPartial("/Views/Shared/Header/Index.cshtml", Model.Header); }

    @RenderBody()

    @{ Html.RenderPartial("/Views/Shared/Footer/Index.cshtml", Model.Footer); }

    <a class="to-top hidden-sm-down" href=""> <img class="image-svg" src="~/images/caret_top.svg" alt="">@HomePage.Index.Top</a>


    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/tether.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/moment.min.js"></script>
    <script src="~/js/bootstrap-datetimepicker.js"></script>
    <script src="~/js/main.js"></script>
    <script src="~/lib/nicelabel/js/jquery.nicelabel.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Livis.Market/Livis.Market/Views/Shared/_LisvisServerLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Livis Server</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/LivisServer/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/LivisServer/css/site.css" />
   
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/LivisServer/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/LivisServer/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="LivisServer" asp-action="Index" class="navbar-brand">Livis Server</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Product" asp-action="Index">Product List</a></li>
                    <li><a asp-area="" asp-controller="Product" asp-action="Create">Create Product</a></li>
                    <li><a asp-area="" asp-controller="Organisation" asp-action="Index">Organisation List</a></li>
                    <li><a asp-area="" asp-controller="Organisation" asp-action="Create">Create Organisation</a></li>
                    <li><a asp-area="" asp-controller="FindUser" asp-action="Index">Search User</a></li>
                    <li><a asp-area="" asp-controller="Account" asp-action="Logout">Logout</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Livis Server</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/LivisServer/lib/jquery/dist/jquery.js"></script>
        <script src="~/LivisServer/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/LivisServer/lib/ckeditor/ckeditor.js"></script>
        <script src="~/LivisServer/lib/ckeditor/adapters/jquery.js"></script>
        <script src="~/LivisServer/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/LivisServer/js/site.min.js" asp-append-version="true"></script>
    </environment>
    <link rel="stylesheet" href="~/LivisServer/lib/image-picker/image-picker.css">
    <script src="~/LivisServer/lib/image-picker/image-picker.js"></script>
    <link rel="stylesheet" href="~/LivisServer/lib/datatables-1.10.16/datatables.min.css">
    <script src="~/LivisServer/lib/datatables-1.10.16/datatables.min.js"></script>
    <link rel="stylesheet" href="~/LivisServer/lib/bootstrap-tagsinput.css">
    <script src="~/LivisServer/lib/bootstrap-tagsinput.js"></script>
    <link rel="stylesheet" href="~/LivisServer/lib/color-picker/css/bootstrap-colorpicker.min.css">
    <script src="~/LivisServer/lib/color-picker/js/bootstrap-colorpicker.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>